apiVersion: batch/v1
kind: Job
metadata:
  name: presync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  template:
    metadata: {}
    spec:
      containers:
      - image: busybox
        name: presync-job
        resources: {}
        command: ["/bin/sh", "-c", "echo 'Running database migrations...' && sleep 10"]
      restartPolicy: Never
status: {}
